# Practice the 80 Pandas quesiton

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("E:/AI_ML_Training/AI_ML/raw_materials/IPL2025Batters.csv")
data.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

### 1. Display the first five rows.

In [3]:
data.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

### 2. Display the last five rows.

In [4]:
data.tail()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

### 3. Find the number of rows and columns.

In [5]:
data.shape

(156, 14)

### 4. Display column names.

In [7]:
data.columns

Index(['Player Name', 'Team', 'Runs', 'Matches', 'Inn', 'No', 'HS', 'AVG',
       'BF', 'SR', '100s', '50s', '4s', '6s'],
      dtype='object')

### 5. Display data types.

In [8]:
data.dtypes

Player Name     object
Team            object
Runs             int64
Matches          int64
Inn              int64
No               int64
HS              object
AVG             object
BF               int64
SR             float64
100s             int64
50s              int64
4s               int64
6s               int64
dtype: object

### 6. Display dataset information.

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

### 7. Generate summary statistics.

In [11]:
data.describe()

,Runs,Matches,Inn,No,BF,SR,100s,50s,4s,6s
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,161.320513,9.865385,7.153846,1.634615,105.673077,134.394103,0.057692,0.916667,14.391026,8.294872
std,180.352772,4.757455,4.810142,1.658163,112.191838,57.237148,0.233912,1.590124,17.778774,9.515500
min,1.000000,1.000000,1.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000
25%,10.750000,6.000000,2.750000,0.000000,12.000000,100.000000,0.000000,0.000000,1.000000,0.000000
50%,93.500000,11.000000,6.000000,1.000000,63.500000,140.005000,0.000000,0.000000,7.000000,4.000000
75%,254.250000,14.000000,12.000000,3.000000,164.750000,162.707500,0.000000,1.000000,23.000000,14.000000
max,759.000000,17.000000,17.000000,7.000000,486.000000,400.000000,1.000000,8.000000,88.000000,40.000000

### 8. Check missing values.

In [12]:
data.isnull().sum()

Player Name    0
Team           0
Runs           0
Matches        0
Inn            0
No             0
HS             0
AVG            0
BF             0
SR             0
100s           0
50s            0
4s             0
6s             0
dtype: int64

### 9. Display only the Name column.

In [13]:
data["Player Name"]

0          Sai Sudharsan
1      Surya Kumar Yadav
2            Virat Kohli
3           Shubman Gill
4         Mitchell Marsh
             ...
151        Khaleel Ahmed
152         Mohit Sharma
153     Donovan Ferreira
154        Digvesh Singh
155       Manoj Bhandage
Name: Player Name, Length: 156, dtype: object

### 10. Display Name and Inning columns.

In [14]:
data[["Player Name", "Inn"]]

           Player Name  Inn
0        Sai Sudharsan   15
1    Surya Kumar Yadav   16
2          Virat Kohli   15
3         Shubman Gill   15
4       Mitchell Marsh   13
..                 ...  ...
151      Khaleel Ahmed    2
152       Mohit Sharma    2
153   Donovan Ferreira    1
154      Digvesh Singh    2
155     Manoj Bhandage    1

[156 rows x 2 columns]

### 11. Find player names average greater than 30.

In [17]:
data[data["AVG"] > '30']

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,Shahbaz Ahmed,LSG,9,3,1,0,9,9.00,8,112.50,0,0,1,0
122,Wiaan Mulder,SRH,9,1,1,0,9,9.00,11,81.81,0,0,1,0
126,Tushar Deshpande,RR,7,10,4,3,3,7.00,8,87.50,0,0,0,0
129,Akash Deep,LSG,6,6,2,1,6*,6.00,2,300.00,0,0,0,1
133,Rovman Powell,KKR,5,2,1,0,5,5.00,5,100.00,0,0,1,0

### 12. Find RCB Player Name.

In [18]:
data[data["Team"] == 'RCB']

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
16,Phil Salt,RCB,403,13,13,1,65,33.58,229,175.98,0,4,48,22
28,Rajat Patidar,RCB,312,15,14,1,64,24.00,217,143.77,0,2,25,14
38,Jitesh Sharma,RCB,261,15,11,4,85*,37.29,148,176.35,0,1,24,17
41,Devdutt Padikkal,RCB,247,10,10,1,61,27.44,164,150.60,0,2,21,14
56,Tim David,RCB,187,12,9,6,50*,62.33,101,185.14,0,1,16,14
72,Liam Livingstone,RCB,112,10,8,1,54,16.00,84,133.33,0,1,4,9
73,Krunal Pandya,RCB,109,15,7,1,73*,18.17,86,126.74,0,1,9,4
77,Mayank Agarwal,RCB,95,4,4,1,41*,31.67,64,148.43,0,0,10,2
84,Romario Shepherd,RCB,70,8,3,1,53*,35.00,24,291.66,0,1,5,7
86,Jacob Bethell,RCB,67,2,2,0,55,33.50,39,171.79,0,1,9,3
112,Bhuvneshwar Kumar,RCB,14,14,6,3,8,4.67,25,56.00,0,0,1,0
138,Yash Dayal,RCB,4,15,3,1,3,2.00,8,50.00,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

### 13. Find Player that have more than 500 runs.

In [20]:
data[data["Runs"] > 500]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24
10,Nicholas Pooran,LSG,524,14,14,2,87*,43.67,267,196.25,0,5,45,40

### 14. Display only opening player.

In [22]:
data[data['No'] == 1]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
15,Rohit Sharma,MI,418,15,15,1,81,29.86,280,149.28,0,4,41,22
16,Phil Salt,RCB,403,13,13,1,65,33.58,229,175.98,0,4,48,22
18,Ajinkya Rahane,KKR,390,13,12,1,61,35.45,264,147.72,0,3,36,20
19,Ryan Rickelton,MI,388,14,14,1,62*,29.85,257,150.97,0,3,47,17
27,Ayush Badoni,LSG,329,14,11,1,74,32.90,222,148.19,0,2,27,14
28,Rajat Patidar,RCB,312,15,14,1,64,24.00,217,143.77,0,2,25,14
29,Abishek Porel,DC,301,13,13,1,51,25.08,205,146.82,0,1,28,12
34,Sanju Samson,RR,285,9,9,1,66,35.63,203,140.39,0,1,27,13
37,Axar Patel,DC,263,12,11,1,43,26.30,167,157.48,0,0,23,15
41,Devdutt Padikkal,RCB,247,10,10,1,61,27.44,164,150.60,0,2,21,14
42,Sunil Narine,KKR,246,12,12,1,44,22.36,144,170.83,0,0,25,19
46,Will Jacks,MI,233,13,11,1,53,23.30,172,135.46,0,1,22,11
49,Nitish Rana,RR,217,11,11,1,81,21.70,134,161.94,0,2,27,9
55,Rachin Ravindra,CSK,191,8,8,1,65*,27.29,149,128.18,0,1,18,4
59,Andre Russell,KKR,167,13,10,1,57*,18.56,102,163.72,0,1,16,14
64,Quinton De Kock,KKR,152,8,8,1,97*,21.71,117,129.91,0,1,9,11
65,Vipraj Nigam,DC,142,14,8,1,39,20.29,79,179.74,0,0,15,8
69,Sameer Rizvi,DC,121,5,4,1,58*,40.33,79,153.16,0,1,11,7
72,Liam Livingstone,RCB,112,10,8,1,54,16.00,84,133.33,0,1,4,9
73,Krunal Pandya,RCB,109,15,7,1,73*,18.17,86,126.74,0,1,9,4
77,Mayank Agarwal,RCB,95,4,4,1,41*,31.67,64,148.43,0,0,10,2
78,Manish Pandey,KKR,92,3,3,1,37,46.00,65,141.53,0,0,5,5
82,Rahmanullah Gurbaz,KKR,74,5,5,1,35,18.50,53,139.62,0,0,10,3
84,Romario Shepherd,RCB,70,8,3,1,53*,35.00,24,291.66,0,1,5,7
87,Jofra Archer,RR,63,12,7,1,30,10.50,50,126.00,0,0,3,4
89,Azmatullah Omarzai,PBKS,57,9,5,1,21*,14.25,41,139.02,0,0,6,3
114,Ravi Bishnoi,LSG,13,11,3,1,13,6.50,16,81.25,0,0,0,2
115,Harpreet Brar,PBKS,11,8,2,1,7*,11.00,13,84.61,0,0,0,1
120,Kagiso Rabada,GT,9,4,2,1,7*,9.00,8,112.50,0,0,0,1
124,Kwena Maphaka,RR,8,2,1,1,8*,-,2,400.00,0,0,2,0
125,Raj Angad Bawa,MI,8,3,1,1,8*,-,4,200.00,0,0,0,0
129,Akash Deep,LSG,6,6,2,1,6*,6.00,2,300.00,0,0,0,1
130,Sandeep Sharma,RR,6,10,1,1,6*,-,5,120.00,0,0,0,0
137,Lockie Ferguson,PBKS,4,4,1,1,4*,-,1,400.00,0,0,1,0
138,Yash Dayal,RCB,4,15,3,1,3,2.00,8,50.00,0,0,0,0
139,Akash Madhwal,RR,4,4,1,1,4*,-,9,44.44,0,0,0,0
141,Mohammed Siraj,GT,3,15,1,1,3*,-,4,75.00,0,0,0,0
143,Simarjeet Singh,SRH,3,4,3,1,3*,1.50,7,42.85,0,0,0,0
144,Fazalhaq Farooqi,RR,2,5,1,1,2*,-,2,100.00,0,0,0,0
145,Trent Boult,MI,2,16,2,1,1*,2.00,3,66.66,0,0,0,0
147,Arshdeep Singh,PBKS,2,17,2,1,1*,2.00,6,33.33,0,0,0,0
148,Varun Chakaravarthy,KKR,1,13,1,1,1*,-,1,100.00,0,0,0,0
149,V Satyanarayana Penmetsa,MI,1,2,1,1,1*,-,1,100.00,0,0,0,0
150,Karn Sharma,MI,1,6,1,1,1*,-,1,100.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0

### 15. Count total Players.

In [25]:
len(data["Player Name"])

156

### 16. Find maximum(orange cap) runs.

In [26]:
data["Runs"].max()

759

### 17. Find maximum(orange cap) runs.

In [27]:
data["Runs"].min()

1

### 18. Find the average of the Runs.

In [28]:
data["Runs"].mean()

np.float64(161.32051282051282)

### 19. Find Median of the Runs.

In [30]:
data["Runs"].median()

93.5