In [1]:
import pandas as pd 
import numpy as np

In [11]:
# Empty Series

empty_s = pd.Series([])
type(empty_s)
empty_s

Series([], dtype: object)

In [13]:
#  Change Datatype through dtype = 'float', from int in series.

series = pd.Series([1,2,3,4], index = ['a','b','c','d'], dtype = float, name = "data")
print(series)

a    1.0
b    2.0
c    3.0
d    4.0
Name: data, dtype: float64

In [16]:
empty_df = pd.DataFrame()
print(empty_df)

Empty DataFrame
Columns: []
Index: []

In [33]:
df = pd.read_csv("E:/AI_ML_Training/raw_materials/Day_6/Fortune_10.csv")

In [22]:
## nrows --> use to access the rows.

df_1 = pd.read_csv("E:/AI_ML_Training/raw_materials/Day_6/Fortune_10.csv", nrows = 2)
df_1

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%

In [25]:
# usecols --> use to access the perticular colmun.

df_1 = pd.read_csv("E:/AI_ML_Training/raw_materials/Day_6/Fortune_10.csv", usecols = [1,2])
df_1

              Name             Industry
0          Lamtone          IT Services
1        Stripfind   Financial Services
2  Canecorporation               Health
3         Mattouch          IT Services
4        Techdrill               Health
5         Techline               Health
6          Cityace               Health
7   Kayelectronics               Health
8          Ganzlax          IT Services
9      Trantraxlax  Government Services

In [17]:
import os

In [18]:
print(os.getcwd())

E:\AI_ML_Training\codes

In [36]:
print(df.sort_values('Inception', ascending = True))

   ID             Name             Industry  Inception       Revenue  \
5   6         Techline               Health       2006  $13,898,119
0   1          Lamtone          IT Services       2009  $11,757,018
4   5        Techdrill               Health       2009  $10,573,990
7   8   Kayelectronics               Health       2009   $9,451,943
1   2        Stripfind   Financial Services       2010  $12,329,371
6   7          Cityace               Health       2010   $9,254,614
8   9          Ganzlax          IT Services       2011  $14,001,180
9  10      Trantraxlax  Government Services       2011  $11,088,336
2   3  Canecorporation               Health       2012  $10,597,009
3   4         Mattouch          IT Services       2013  $14,026,934

            Expenses    Profit Growth
5  5,470,303 Dollars   8427816    23%
0  6,482,465 Dollars   5274553    30%
4  7,435,363 Dollars   3138627     8%
7  3,878,113 Dollars   5573830     4%
1    916,455 Dollars  11412916    20%
6  6,249,498 Dollars   3005116     6%
8                NaN  11901180    18%
9  5,635,276 Dollars   5453060     7%
2  7,591,189 Dollars   3005820     7%
3  7,429,377 Dollars   6597557    26%

In [32]:
# skiprows --> use to skip the rows and make the next one header. we also can pass the list of the rows to skip.

df_1 = pd.read_csv("E:/AI_ML_Training/raw_materials/Day_6/Fortune_10.csv", skiprows = 1)
df_1

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [39]:
# index_col --> use to make the col a index column, here we can pass the index of the column or name of the col.

df_1 = pd.read_csv("E:/AI_ML_Training/raw_materials/Day_6/Fortune_10.csv", index_col = 'Name')
df_1

,ID,Industry,Inception,Revenue,Expenses,Profit,Growth
Name,,,,,,,
Lamtone,1,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
Stripfind,2,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
Canecorporation,3,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
Mattouch,4,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
Techdrill,5,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
Techline,6,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
Cityace,7,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
Kayelectronics,8,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
Ganzlax,9,IT Services,2011,"$14,001,180",NaN,11901180,18%
Trantraxlax,10,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [41]:
# header --> use to convert the row in labels. also giving 'None' we can remove the header

df_1 = pd.read_csv("E:/AI_ML_Training/raw_materials/Day_6/Fortune_10.csv", header = 1)
df_1

,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
0,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
1,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
2,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
3,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
4,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
5,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
6,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
7,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
8,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [42]:
# names --> use to give the name to the column, it will assign the name from the back.

df_1 = pd.read_csv("E:/AI_ML_Training/raw_materials/Day_6/Fortune_10.csv", names = ['A', 'B'])
df_1

,,,,,,A,B
ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [48]:
# dtype -->  use to change the datatype of the col, by given dictionary of col names and dtypes we can convert multiple columns.

df_1 = pd.read_csv("E:/AI_ML_Training/raw_materials/Day_6/Fortune_10.csv", dtype = {'ID' : 'string', 'Profit': 'float64', 'Inception': 'float64'})
df_1

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009.0,"$11,757,018","6,482,465 Dollars",5274553.0,30%
1,2,Stripfind,Financial Services,2010.0,"$12,329,371","916,455 Dollars",11412916.0,20%
2,3,Canecorporation,Health,2012.0,"$10,597,009","7,591,189 Dollars",3005820.0,7%
3,4,Mattouch,IT Services,2013.0,"$14,026,934","7,429,377 Dollars",6597557.0,26%
4,5,Techdrill,Health,2009.0,"$10,573,990","7,435,363 Dollars",3138627.0,8%
5,6,Techline,Health,2006.0,"$13,898,119","5,470,303 Dollars",8427816.0,23%
6,7,Cityace,Health,2010.0,"$9,254,614","6,249,498 Dollars",3005116.0,6%
7,8,Kayelectronics,Health,2009.0,"$9,451,943","3,878,113 Dollars",5573830.0,4%
8,9,Ganzlax,IT Services,2011.0,"$14,001,180",NaN,11901180.0,18%
9,10,Trantraxlax,Government Services,2011.0,"$11,088,336","5,635,276 Dollars",5453060.0,7%

In [50]:
os.chdir("E:/AI_ML_Training")

In [53]:
data = pd.read_csv('raw_materials/Day_6/Fortune_10.csv')
data

,ID,Name,Industry,Inception,Revenue,Expenses,Profit,Growth
0,1,Lamtone,IT Services,2009,"$11,757,018","6,482,465 Dollars",5274553,30%
1,2,Stripfind,Financial Services,2010,"$12,329,371","916,455 Dollars",11412916,20%
2,3,Canecorporation,Health,2012,"$10,597,009","7,591,189 Dollars",3005820,7%
3,4,Mattouch,IT Services,2013,"$14,026,934","7,429,377 Dollars",6597557,26%
4,5,Techdrill,Health,2009,"$10,573,990","7,435,363 Dollars",3138627,8%
5,6,Techline,Health,2006,"$13,898,119","5,470,303 Dollars",8427816,23%
6,7,Cityace,Health,2010,"$9,254,614","6,249,498 Dollars",3005116,6%
7,8,Kayelectronics,Health,2009,"$9,451,943","3,878,113 Dollars",5573830,4%
8,9,Ganzlax,IT Services,2011,"$14,001,180",NaN,11901180,18%
9,10,Trantraxlax,Government Services,2011,"$11,088,336","5,635,276 Dollars",5453060,7%

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         10 non-null     int64
 1   Name       10 non-null     object
 2   Industry   10 non-null     object
 3   Inception  10 non-null     int64
 4   Revenue    10 non-null     object
 5   Expenses   9 non-null      object
 6   Profit     10 non-null     int64
 7   Growth     10 non-null     object
dtypes: int64(3), object(5)
memory usage: 772.0+ bytes