## Pandas Basics
---
* What is Pandas
* Why Pandas
* Series
* DataFrame
* Exploring Data
* Modifying Data
* Selection Data
* Sorting Data
* Aggregating Data
* Applying functions

1) Pandas is a pyhton powerful library use for data manipulation.
2)

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive

In [ ]:
# drive.mount('/content/drive')

## Series 1d 2d
---

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)
print(type(arr1))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>

In [ ]:
data = [10,20,30,40,50,60,70,80,90]

In [ ]:
arr_s1 = pd.Series(arr1)
print(arr_s1)
print(type(arr_s1))

list_s1 = pd.Series(data)
print(list_s1)
print(type(list_s1))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2_s2 = pd.DataFrame(arr2, columns=['a','b','c'],index=['x','y','z'])
print(arr2_s2)

   a  b  c
x  1  2  3
y  4  5  6
z  7  8  9

In [ ]:
data1 = [[1,2,3,4],[5,6,7,8]]
data1_s = pd.Series(data1)

print(data1_s)

0    [1, 2, 3, 4]
1    [5, 6, 7, 8]
dtype: object

---
## Dataframe
---

In [ ]:
merge_data = pd.DataFrame((arr_s1, list_s1))
print(merge_data)

    0   1   2   3   4   5   6   7   8
0   1   2   3   4   5   6   7   8   9
1  10  20  30  40  50  60  70  80  90

In [ ]:
data2 = [('Mahipal',78),('Soumar',58),('Halak',105),('Shailesh',73),('Vijay',39),('Nishant',83)]
data2_df = pd.DataFrame(data2, columns=['Name','Roll No.'])
print(data2_df)

       Name  Roll No.
0   Mahipal        78
1    Soumar        58
2     Halak       105
3  Shailesh        73
4     Vijay        39
5   Nishant        83

In [ ]:
data3 = {
    'Name':['Mahipal','Soumar','Halak','Shailesh','Vijay','Nishant'],
    'Roll No.':[78,58,105,73,39,83]
}
data3_df = pd.DataFrame(data3)
print(data3_df)

       Name  Roll No.
0   Mahipal        78
1    Soumar        58
2     Halak       105
3  Shailesh        73
4     Vijay        39
5   Nishant        83

In [ ]:
data4 = [['Mahipal',78],['Soumar',58],['Halak',105],['Shailesh',73],['Vijay',39],['Nishant',83]]
data4_df = pd.DataFrame(data4, columns = ['Name', 'Roll No.'])
print(data4_df)

       Name  Roll No.
0   Mahipal        78
1    Soumar        58
2     Halak       105
3  Shailesh        73
4     Vijay        39
5   Nishant        83

In [ ]:
arr3 = np.array([1,2,3,4,5])
arr4 = np.array([5,6,7,8,9])
arr3_4 = {
    'a':arr3,
    'b':arr4
}
arr3_4_df = pd.DataFrame(arr3_4)
print(arr3_4_df)

   a  b
0  1  5
1  2  6
2  3  7
3  4  8
4  5  9

---
##  Reading Data
---

In [ ]:
# from google.colab import files
# uploaded = files.upload()


IPL_data = pd.read_csv('./IPL2025Batters.csv')
IPL_data.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [ ]:
AIR = pd.read_json('./airports.json')
print(AIR)

                                             airports
0   {'code': 'ATL', 'name': 'Hartsfield-Jackson At...
1   {'code': 'PEK', 'name': 'Beijing Capital Inter...
2   {'code': 'DXB', 'name': 'Dubai International',...
3   {'code': 'LAX', 'name': 'Los Angeles Internati...
4   {'code': 'HND', 'name': 'Tokyo Haneda', 'city'...
5   {'code': 'ORD', 'name': 'O'Hare International'...
6   {'code': 'LHR', 'name': 'London Heathrow', 'ci...
7   {'code': 'PVG', 'name': 'Shanghai Pudong Inter...
8   {'code': 'CDG', 'name': 'Paris Charles de Gaul...
9   {'code': 'DFW', 'name': 'Dallas/Fort Worth Int...
10  {'code': 'CAN', 'name': 'Guangzhou Baiyun Inte...
11  {'code': 'AMS', 'name': 'Amsterdam Schiphol', ...
12  {'code': 'FRA', 'name': 'Frankfurt Airport', '...
13  {'code': 'IST', 'name': 'Istanbul Airport', 'c...
14  {'code': 'SIN', 'name': 'Singapore Changi', 'c...
15  {'code': 'ICN', 'name': 'Incheon International...
16  {'code': 'DEN', 'name': 'Denver International'...
17  {'code': 'BKK', 'name': 'Suvarnabhumi Airport'...
18  {'code': 'JFK', 'name': 'John F. Kennedy Inter...
19  {'code': 'HKG', 'name': 'Hong Kong Internation...
20  {'code': 'KUL', 'name': 'Kuala Lumpur Internat...
21  {'code': 'MAD', 'name': 'Adolfo Suárez Madrid–...
22  {'code': 'SFO', 'name': 'San Francisco Interna...
23  {'code': 'MIA', 'name': 'Miami International',...
24  {'code': 'SYD', 'name': 'Sydney Kingsford Smit...
25  {'code': 'MUC', 'name': 'Munich Airport', 'cit...
26  {'code': 'BCN', 'name': 'Barcelona–El Prat', '...
27  {'code': 'YYZ', 'name': 'Toronto Pearson Inter...
28  {'code': 'MEX', 'name': 'Mexico City Internati...
29  {'code': 'NRT', 'name': 'Narita International'...

---
## Exploring Data
---

In [ ]:
IPL_data.columns

Index(['Player Name', 'Team', 'Runs', 'Matches', 'Inn', 'No', 'HS', 'AVG',
       'BF', 'SR', '100s', '50s', '4s', '6s'],
      dtype='object')

In [ ]:
IPL_data.dtypes

Player Name     object
Team            object
Runs             int64
Matches          int64
Inn              int64
No               int64
HS              object
AVG             object
BF               int64
SR             float64
100s             int64
50s              int64
4s               int64
6s               int64
dtype: object

In [ ]:
IPL_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

In [ ]:
AIR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   airports  30 non-null     object
dtypes: object(1)
memory usage: 372.0+ bytes

In [ ]:
IPL_data.describe()

,Runs,Matches,Inn,No,BF,SR,100s,50s,4s,6s
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,161.320513,9.865385,7.153846,1.634615,105.673077,134.394103,0.057692,0.916667,14.391026,8.294872
std,180.352772,4.757455,4.810142,1.658163,112.191838,57.237148,0.233912,1.590124,17.778774,9.515500
min,1.000000,1.000000,1.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000
25%,10.750000,6.000000,2.750000,0.000000,12.000000,100.000000,0.000000,0.000000,1.000000,0.000000
50%,93.500000,11.000000,6.000000,1.000000,63.500000,140.005000,0.000000,0.000000,7.000000,4.000000
75%,254.250000,14.000000,12.000000,3.000000,164.750000,162.707500,0.000000,1.000000,23.000000,14.000000
max,759.000000,17.000000,17.000000,7.000000,486.000000,400.000000,1.000000,8.000000,88.000000,40.000000

In [ ]:
IPL_data.shape

(156, 14)

In [ ]:
IPL_data.head()  # --> use to access the starting rows

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37

In [ ]:
IPL_data.tail() # --> use to access the ending rows

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [ ]:
IPL_data.isnull().sum()  # -->only isnull() will show you where is the null present, .sum() show you the total no. of null in each coloumn, if using to .sum() then it will show the agregate sum.

Player Name    0
Team           0
Runs           0
Matches        0
Inn            0
No             0
HS             0
AVG            0
BF             0
SR             0
100s           0
50s            0
4s             0
6s             0
dtype: int64

In [ ]:
IPL_data.isna()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,False,False,False,False,False,False,False,False,False,False,False,False,False,False
152,False,False,False,False,False,False,False,False,False,False,False,False,False,False
153,False,False,False,False,False,False,False,False,False,False,False,False,False,False
154,False,False,False,False,False,False,False,False,False,False,False,False,False,False
155,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
IPL_data.dropna()  ## --> .dropna(0, inplace = True) meaning to make the change in the main dataset. dropna will delete whole row that contain the null value

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [ ]:
IPL_data.fillna(0)  # --> replace the null values

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

---
## Selecting Data
---

In [ ]:
IPL_data[['Player Name','Team']]

           Player Name Team
0        Sai Sudharsan   GT
1    Surya Kumar Yadav   MI
2          Virat Kohli  RCB
3         Shubman Gill   GT
4       Mitchell Marsh  LSG
..                 ...  ...
151      Khaleel Ahmed  CSK
152       Mohit Sharma   DC
153   Donovan Ferreira   DC
154      Digvesh Singh  LSG
155     Manoj Bhandage  RCB

[156 rows x 2 columns]

In [ ]:
selected_d = IPL_data[['Player Name', 'Team', 'Runs']]
selected_d

           Player Name Team  Runs
0        Sai Sudharsan   GT   759
1    Surya Kumar Yadav   MI   717
2          Virat Kohli  RCB   657
3         Shubman Gill   GT   650
4       Mitchell Marsh  LSG   627
..                 ...  ...   ...
151      Khaleel Ahmed  CSK     1
152       Mohit Sharma   DC     1
153   Donovan Ferreira   DC     1
154      Digvesh Singh  LSG     1
155     Manoj Bhandage  RCB     1

[156 rows x 3 columns]

In [ ]:
IPL_data['Runs'].mean()

np.float64(161.32051282051282)

In [ ]:
print(IPL_data.sort_values('Runs', ascending=True))

                  Player Name Team  Runs  Matches  Inn  No    HS    AVG   BF  \
151             Khaleel Ahmed  CSK     1       14    2   2    1*      -    2
150               Karn Sharma   MI     1        6    1   1    1*      -    1
149  V Satyanarayana Penmetsa   MI     1        2    1   1    1*      -    1
148       Varun Chakaravarthy  KKR     1       13    1   1    1*      -    1
155            Manoj Bhandage  RCB     1        1    1   0     1   1.00    4
..                        ...  ...   ...      ...  ...  ..   ...    ...  ...
4              Mitchell Marsh  LSG   627       13   13   0   117  48.23  383
3                Shubman Gill   GT   650       15   15   2   93*  50.00  417
2                 Virat Kohli  RCB   657       15   15   3   73*  54.75  454
1           Surya Kumar Yadav   MI   717       16   16   5   73*  65.18  427
0               Sai Sudharsan   GT   759       15   15   1  108*  54.21  486

         SR  100s  50s  4s  6s
151   50.00     0    0   0   0
150  100.00     0    0   0   0
149  100.00     0    0   0   0
148  100.00     0    0   0   0
155   25.00     0    0   0   0
..      ...   ...  ...  ..  ..
4    163.70     1    6  56  37
3    155.87     0    6  62  24
2    144.71     0    8  66  19
1    167.91     0    5  69  38
0    156.17     1    6  88  21

[156 rows x 14 columns]

### HOMEWORK --> make a notebook and read on different format files.

In [ ]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']